name: Build & Push Image (Reusable)

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag to use for the Docker image'
        required: true
        type: string
      environment:
        description: 'The environment for the workflow'
        required: true
        type: string
      dockerfile:
        description: 'Path to the Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  build_and_push:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - id: build
        run: |
          IMAGE_TAG=${{ inputs.image_tag }}
          echo "Building Docker image with tag $IMAGE_TAG..."
          docker build -t ${{ vars.ECR_REPO }}:$IMAGE_TAG -f ${{ inputs.dockerfile }} .
          echo "Built image: ${{ vars.ECR_REPO }}:$IMAGE_TAG"
        shell: bash

      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ inputs.image_tag }}
          docker push ${{ vars.ECR_REPO }}:$IMAGE_TAG
        shell: bash
