name: Check If Need Deploy

on:
  workflow_call:
    outputs:
      deploy:
        description: "Whether to deploy or not"
        value: ${{ jobs.check_if_need_deploy.outputs.deploy }}

jobs:
  check_if_need_deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - uses: actions/checkout@v4

      - id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching commits from the pull request via GitHub API..."
          PR_NUMBER=${{ github.event.pull_request.number }}
          commits=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits \
            | jq -r '.[].commit.message')

          echo "Commit messages from PR:"
          echo "$commits"

          if echo "$commits" | grep -Eiq "(feat|fix|BREAKING CHANGE)"; then
            echo "✅ Relevant change found. Proceeding with deploy."
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ No relevant changes. Skipping deploy."
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi
