name: Verify .NET Project (Reusable)

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'The .NET version to set up (e.g. 9.0.x)'
        required: false
        type: string
        default: '9.0.x'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Build & Test .NET
        run: |
          dotnet restore
          dotnet build
          dotnet test
